In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import datetime

2023-03-27 12:05:48.804708: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-03-27 12:05:48.806455: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-03-27 12:05:48.841157: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-03-27 12:05:48.841966: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-27 12:05:49.417693: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Co

In [2]:
print(tf.__version__)

2.12.0


In [3]:
car_data = pd.read_csv('car_data.csv')

In [4]:
car_data.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [5]:
car_data = car_data.iloc[:, 1:]

In [6]:
car_data.head()

Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0  2014           3.35           5.59       27000    Petrol      Dealer   
1  2013           4.75           9.54       43000    Diesel      Dealer   
2  2017           7.25           9.85        6900    Petrol      Dealer   
3  2011           2.85           4.15        5200    Petrol      Dealer   
4  2014           4.60           6.87       42450    Diesel      Dealer   

  Transmission  Owner  
0       Manual      0  
1       Manual      0  
2       Manual      0  
3       Manual      0  
4       Manual      0

In [7]:
car_data['current_year'] = datetime.datetime.today().year

In [8]:
car_data.head()

Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0  2014           3.35           5.59       27000    Petrol      Dealer   
1  2013           4.75           9.54       43000    Diesel      Dealer   
2  2017           7.25           9.85        6900    Petrol      Dealer   
3  2011           2.85           4.15        5200    Petrol      Dealer   
4  2014           4.60           6.87       42450    Diesel      Dealer   

  Transmission  Owner  current_year  
0       Manual      0          2023  
1       Manual      0          2023  
2       Manual      0          2023  
3       Manual      0          2023  
4       Manual      0          2023

In [9]:
car_data['car_age'] = car_data['current_year'] - car_data['Year']

In [10]:
car_data.head()

Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0  2014           3.35           5.59       27000    Petrol      Dealer   
1  2013           4.75           9.54       43000    Diesel      Dealer   
2  2017           7.25           9.85        6900    Petrol      Dealer   
3  2011           2.85           4.15        5200    Petrol      Dealer   
4  2014           4.60           6.87       42450    Diesel      Dealer   

  Transmission  Owner  current_year  car_age  
0       Manual      0          2023        9  
1       Manual      0          2023       10  
2       Manual      0          2023        6  
3       Manual      0          2023       12  
4       Manual      0          2023        9

In [11]:
car_data.drop(['Year'], axis=1, inplace=True)

In [12]:
car_data.head()

Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0           3.35           5.59       27000    Petrol      Dealer   
1           4.75           9.54       43000    Diesel      Dealer   
2           7.25           9.85        6900    Petrol      Dealer   
3           2.85           4.15        5200    Petrol      Dealer   
4           4.60           6.87       42450    Diesel      Dealer   

  Transmission  Owner  current_year  car_age  
0       Manual      0          2023        9  
1       Manual      0          2023       10  
2       Manual      0          2023        6  
3       Manual      0          2023       12  
4       Manual      0          2023        9

In [13]:
get_dumm_data = car_data

In [14]:
get_dumm_data=pd.get_dummies(get_dumm_data, drop_first=True)

In [15]:
get_dumm_data.head()

Selling_Price  Present_Price  Kms_Driven  Owner  current_year  car_age  \
0           3.35           5.59       27000      0          2023        9   
1           4.75           9.54       43000      0          2023       10   
2           7.25           9.85        6900      0          2023        6   
3           2.85           4.15        5200      0          2023       12   
4           4.60           6.87       42450      0          2023        9   

   Fuel_Type_Diesel  Fuel_Type_Petrol  Seller_Type_Individual  \
0                 0                 1                       0   
1                 1                 0                       0   
2                 0                 1                       0   
3                 0                 1                       0   
4                 1                 0                       0   

   Transmission_Manual  
0                    1  
1                    1  
2                    1  
3                    1  
4                    1

In [16]:
car_data_features = get_dumm_data.iloc[:, 1:].values

In [17]:
car_data_features

array([[5.5900e+00, 2.7000e+04, 0.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        1.0000e+00],
       [9.5400e+00, 4.3000e+04, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [9.8500e+00, 6.9000e+03, 0.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        1.0000e+00],
       ...,
       [1.1000e+01, 8.7934e+04, 0.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        1.0000e+00],
       [1.2500e+01, 9.0000e+03, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [5.9000e+00, 5.4640e+03, 0.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        1.0000e+00]])

In [18]:
car_data_labels = get_dumm_data.iloc[:, 0:1].values

In [19]:
car_data_labels

array([[ 3.35],
       [ 4.75],
       [ 7.25],
       [ 2.85],
       [ 4.6 ],
       [ 9.25],
       [ 6.75],
       [ 6.5 ],
       [ 8.75],
       [ 7.45],
       [ 2.85],
       [ 6.85],
       [ 7.5 ],
       [ 6.1 ],
       [ 2.25],
       [ 7.75],
       [ 7.25],
       [ 7.75],
       [ 3.25],
       [ 2.65],
       [ 2.85],
       [ 4.9 ],
       [ 4.4 ],
       [ 2.5 ],
       [ 2.9 ],
       [ 3.  ],
       [ 4.15],
       [ 6.  ],
       [ 1.95],
       [ 7.45],
       [ 3.1 ],
       [ 2.35],
       [ 4.95],
       [ 6.  ],
       [ 5.5 ],
       [ 2.95],
       [ 4.65],
       [ 0.35],
       [ 3.  ],
       [ 2.25],
       [ 5.85],
       [ 2.55],
       [ 1.95],
       [ 5.5 ],
       [ 1.25],
       [ 7.5 ],
       [ 2.65],
       [ 1.05],
       [ 5.8 ],
       [ 7.75],
       [14.9 ],
       [23.  ],
       [18.  ],
       [16.  ],
       [ 2.75],
       [ 3.6 ],
       [ 4.5 ],
       [ 4.75],
       [ 4.1 ],
       [19.99],
       [ 6.95],
       [ 4.5 ],
       [

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(car_data_features, car_data_labels, test_size=0.2, random_state=0)

In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [24]:
from tensorflow.keras.layers import Input, Dense, Activation,Dropout
from tensorflow.keras.models import Model

In [25]:
# Shape

input_layer = Input(shape=(car_data_features.shape[1],))
dense_layer_1 = Dense(100, activation='relu')(input_layer)
dense_layer_2 = Dense(50, activation='relu')(dense_layer_1)
dense_layer_3 = Dense(25, activation='relu')(dense_layer_2)
output = Dense(1)(dense_layer_3)

In [26]:
model = Model(inputs=input_layer, outputs=output)
model.compile(loss="mean_squared_error" , optimizer="adam", metrics=["mean_squared_error"])

In [27]:
history = model.fit(X_train, y_train, batch_size=2, epochs=100, verbose=1, validation_split=0.2)

Epoch 1/100
96/96 [==============================] - 1s 3ms/step - loss: 38.5126 - mean_squared_error: 38.5126 - val_loss: 8.8412 - val_mean_squared_error: 8.8412
Epoch 2/100
96/96 [==============================] - 0s 1ms/step - loss: 9.8724 - mean_squared_error: 9.8724 - val_loss: 3.0582 - val_mean_squared_error: 3.0582
Epoch 3/100
96/96 [==============================] - 0s 1ms/step - loss: 3.9321 - mean_squared_error: 3.9321 - val_loss: 1.0821 - val_mean_squared_error: 1.0821
Epoch 4/100
96/96 [==============================] - 0s 2ms/step - loss: 1.9338 - mean_squared_error: 1.9338 - val_loss: 0.7123 - val_mean_squared_error: 0.7123
Epoch 5/100
96/96 [==============================] - 0s 2ms/step - loss: 1.7238 - mean_squared_error: 1.7238 - val_loss: 0.7935 - val_mean_squared_error: 0.7935
Epoch 6/100
96/96 [==============================] - 0s 2ms/step - loss: 1.3412 - mean_squared_error: 1.3412 - val_loss: 1.0878 - val_mean_squared_error: 1.0878
Epoch 7/100
96/96 [=============

96/96 [==============================] - 0s 1ms/step - loss: 0.3767 - mean_squared_error: 0.3767 - val_loss: 0.8085 - val_mean_squared_error: 0.8085
Epoch 52/100
96/96 [==============================] - 0s 1ms/step - loss: 0.4314 - mean_squared_error: 0.4314 - val_loss: 0.7104 - val_mean_squared_error: 0.7104
Epoch 53/100
96/96 [==============================] - 0s 1ms/step - loss: 0.3638 - mean_squared_error: 0.3638 - val_loss: 0.5335 - val_mean_squared_error: 0.5335
Epoch 54/100
96/96 [==============================] - 0s 1ms/step - loss: 0.2847 - mean_squared_error: 0.2847 - val_loss: 0.5297 - val_mean_squared_error: 0.5297
Epoch 55/100
96/96 [==============================] - 0s 1ms/step - loss: 0.3268 - mean_squared_error: 0.3268 - val_loss: 0.5986 - val_mean_squared_error: 0.5986
Epoch 56/100
96/96 [==============================] - 0s 1ms/step - loss: 0.3453 - mean_squared_error: 0.3453 - val_loss: 0.4880 - val_mean_squared_error: 0.4880
Epoch 57/100
96/96 [=====================

In [28]:
from sklearn.metrics import mean_squared_error
from math import sqrt

In [29]:
pred_train = model.predict(X_train)

8/8 [==============================] - 0s 1ms/step


In [30]:
print(np.sqrt(mean_squared_error(y_train,pred_train)))

0.536437135320325


In [31]:
pred = model.predict(X_test)

2/2 [==============================] - 0s 4ms/step


In [32]:
print(np.sqrt(mean_squared_error(y_test,pred)))

0.7933363806084837


In [33]:
model.predict([[5.59000,27000,0,2023,9,0,1,0,1]])

1/1 [==============================] - 0s 30ms/step


array([[12786.156]], dtype=float32)

In [34]:
model

In [35]:
car_data_features.shape

(301, 9)

In [36]:
print(model.summary())

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 9)]               0         
                                                                 
 dense (Dense)               (None, 100)               1000      
                                                                 
 dense_1 (Dense)             (None, 50)                5050      
                                                                 
 dense_2 (Dense)             (None, 25)                1275      
                                                                 
 dense_3 (Dense)             (None, 1)                 26        
                                                                 
Total params: 7,351
Trainable params: 7,351
Non-trainable params: 0
_________________________________________________________________
None
